In [1]:
from sklearn.model_selection import ShuffleSplit
import numpy as np

In [2]:
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
y = np.array([1, 2, 1, 2])
cv = ShuffleSplit(n_splits=4, test_size=.25, random_state=0)

for train_index, test_index in cv.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    print(type(train_index))

TRAIN: [3 1 0] TEST: [2]
<class 'numpy.ndarray'>
TRAIN: [2 1 3] TEST: [0]
<class 'numpy.ndarray'>
TRAIN: [0 2 1] TEST: [3]
<class 'numpy.ndarray'>
TRAIN: [0 2 3] TEST: [1]
<class 'numpy.ndarray'>


In [3]:
cv.split(X)

<generator object BaseShuffleSplit.split at 0x00000187888102A0>

In [7]:
X[train_index]

array([[1, 2],
       [5, 6],
       [7, 8]])

In [8]:
X

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [6]:
print(train_index)

[0 2 3]
